### ISSUE TITLE
do we still need readme.rdoc?

### ISSUE THREAD

**Issue by pjurczynski** [netguru-training/equinox-group#1]
hey - could you check the https://github.com/netguru-training/equinox-group/blob/master/README.rdoc and if it's not needed - just remove :).
@llukasxx @kevinkucharczyk @michaupapuga @wwilyW

**Comment by lukasgor** [comment]
done :)

**Comment by pjurczynski** [comment]
great! (done in https://github.com/netguru-training/equinox-group/commit/2ad6cc28bf09773f6597c4ce35aa95f7d288c84f)
