### ISSUE TITLE
binding.pry in the project

### ISSUE THREAD

**Issue by pjurczynski** [netguru-training/equinox-group#2]
https://github.com/netguru-training/equinox-group/blob/master/spec/controllers/search_controller_spec.rb#L13
@llukasxx could you remove that binding.pry?

**Comment by smnkrt** [comment]
Done. I didn't notice it was directed to likasxx. Hope it's not a problem.

**Comment by pjurczynski** [comment]
it's cool :) (commit that fixed the issue: https://github.com/netguru-training/equinox-group/commit/2f0434c7543f5de2f7dd93683895b24c8fee912e)
